### PR TITLE
Addresses bugs for Dropbox provider support with the Hyrax 3.0.0.pre.beta1 release

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Also addresses the following:
- Runs tests against Ruby releases 2.6.1, 2.5.3, 2.4.5, and 2.3.8
- Ensures that Travis CI builds downgrade Bundler from 2.x releases
- Removes unnecessary styling rules
- Ensures that Dropbox downloads are not placed within a directory outside of the Rails app
- Provides a configuration option for the Dropbox provider download directory path
- Restructures the `browse_everything` SCSS files in order to ensure that pre-compilation of assets on new Rails apps do not raise errors (resolves https://github.com/samvera/browse-everything/issues/260)

### CODE REVIEW

**Comment by jrgriffiniii** [comment]
This will not resolve all problems I've encountered with the Hyrax 3.0.0.pre.beta1 release and browse-everything, but it blocks basing a PR from https://github.com/samvera/hyrax/compare/master...jrgriffiniii:browse-everything-1.0.0rc2-errors (which should address the remaining issues).

**Comment by jrochkind** [comment]
> * Provides a configuration option for the Dropbox provider download directory path

Is there a reason this should be provider-specific, instead of a general configuration that applies regardless of provider?  

I'm gathering that general configuration was not already there?

**Comment by jrochkind** [comment]
Would it make sense to break this into fewer PRs, so they can be individually evaluated and merged? Things which fix CI build and/or bugs seem different than adding features, and even within the bugfix and CI build category, some of them may be uncontroversial and able to be immediatley merged, while others may require more thought.

**Comment by jrgriffiniii** [comment]
Deprecated by #262, #263, and #265.

**Pull request closed without merging**
