### PR TITLE
Release version 1.0.0.RC1

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Issues the first candidate for a 1.0.0 release.

### CODE REVIEW

**Comment by jrgriffiniii** [comment]
I'm not aware of RC1 being blocked by anything.  @mbklein ?

**Comment by jrochkind** [comment]
Hooray, thanks! Please do a release to rubygems too of the rc1?

There are several dozen bunch of rubygems "owners" who can actually do the release, but I'm not one of them, or I'd offer to do it for you!

It should be as simple as running `rake release`, since b-e is [set up with the bundler release tasks](https://github.com/samvera/browse-everything/blob/master/Rakefile#L3)

**Comment by jrochkind** [comment]
oh wait, I may be one of them! I can do the release if I get the go ahead to do so!

**Comment by jrgriffiniii** [comment]
Released to https://rubygems.org/gems/browse-everything/versions/1.0.0.rc1, thank you very much @jrochkind and @mbklein!

**Pull request merged**
