### PR TITLE
Adds Ruby 2.7 and Rails 6.0.2 to the CircleCI config.

### LINKED ISSUE #315: Add support for Ruby 2.7.z releases
Ruby 2.7.0 was released on 12/25/2019, and in accordance with the charter of the current phase of the Component Maintenance Working Group, the CircleCI configuration for this should be updated.

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #315 and #316 by adding Ruby 2.7, adding Rails 6.0.2, and updating the existing Ruby and Rails releases on the CircleCI config.

### CODE REVIEW

**Comment by jeremyf** [comment]
@jrgriffiniii This looks stuck. Can you give it another pass.

**Comment by jrgriffiniii** [comment]
Rubocop seems to be breaking for Ruby 2.7.0 versions for this Gem:

```
#!/bin/bash -eo pipefail
bundle exec rubocop
Error: Unknown Ruby version 2.7 found in `/home/circleci/project/Gemfile.lock`.
Supported versions: 2.2, 2.3, 2.4, 2.5, 2.6

Exited with code exit status 2
```
(please see https://circleci.com/gh/jrgriffiniii/browse-everything/1620)

**Comment by jrgriffiniii** [comment]
Routing for the feature specs seems to be now be failing only for Rails 6.0.z releases (please see https://circleci.com/gh/jrgriffiniii/browse-everything/1658, https://circleci.com/gh/jrgriffiniii/browse-everything/1661, https://circleci.com/gh/jrgriffiniii/browse-everything/1663).

**Comment by jrgriffiniii** [comment]
So this is currently blocked by the Rails 6 for importing JavaScript using Webpacker. I've been attempting to port the JavaScript functionality from the Sprockets-based approach into one that uses CommonJS `require` (this is used in the documentation for https://github.com/rails/webpacker/blob/master/docs/webpack.md#plugins).

**Comment by jrgriffiniii** [comment]
Some of the failures which this addressed were related to the latest bixby release being pinned to Gem dependencies which are in conflict with Rails 6.y.z releases.

**Comment by jrgriffiniii** [comment]
This is finally passing - a significant amount of the JavaScript needed to be restructured in order to work properly with Rails 6 and Webpacker.

**Review by cjcolvar — APPROVED** [review]
This looks great!  Thanks @jrgriffiniii for the hard work on this!

**Pull request merged**
