### PR TITLE
[WIP] Fixes `BrowseEverything::FileEntry#relative_parent_path?` for Ruby 2.3.x releases

### LINKED ISSUE #218: Instructions for running tests?
Are there docs for how to run tests in development? If not, can some be added?

If I try to run `bundle exec rspec`, I get:

```
LoadError: cannot load such file -- /Users/jrochkind/code/browse-everything/.internal_test_app/config/environment
  /Users/jrochkind/code/browse-everything/spec/spec_helper.rb:4:in `require'
```

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #218.  Also addresses the following:
- Replaces "Project Hydra" with "Samvera Community" for contribution documentation
- Adds basic testing instructions to the README

### CODE REVIEW

**Comment by jrgriffiniii** [comment]
#220 blocks builds passing on Travis CI using Rails 5.2.0 and 4.2.10, but this should improve the documentation and more trivial cases.

**Comment by jrochkind** [comment]
I think you mean ruby 2.3?

**Comment by jrgriffiniii** [comment]
Yes, apologies for that error.

**Comment by jrochkind** [comment]
github tells me there are no actual commits in this pr?

**Comment by jrgriffiniii** [comment]
It was likely fixed within https://github.com/samvera/browse-everything/pull/231/files#diff-17b11fd765f5c8041fda2930d5adf20e

**Pull request closed without merging**
