### PR TITLE
Adds Kaltura driver.

### PR DESCRIPTION
**Pull request by scherztc**
This adds Kaltura (www.kaltura.com) as a configurable driver for browse_everything.

### CODE REVIEW

**Comment by mbklein** [comment]
@scherztc: I'm happy to merge this if you can fix the failing tests and rebase.

**Comment by scherztc** [comment]
Okay.  Let me try and clean up the userid.warden part.  Thanks.

**Comment by scherztc** [comment]
@mbklein Any idea what is going on with coveralls?  Where do I need to increase coverage?

**Comment by jcoyne** [comment]
@scherztc It looks like coveralls is false negative. I'm getting that on #145 too.

**Pull request closed without merging**
