### PR TITLE
Extends the tests for the Google Drive provider and resolves the web_content_link issue

### LINKED ISSUE #177: Google Drive: link_for method returns empty url
Since moving up to Google Drive Api version 3 the link_for method is returns an empty url.

This empty url does not let browse_everything retrieve the file.

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves (some of) #177

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@jrgriffiniii Looks good! What else remains to resolve #177?

**Comment by scherztc** [comment]
@mjgiarlo :  I think there still needs to be some work done in ImportURLJob to deal with the fact that Google is doing some url redirection, too.  Here is what we did in Hyrax 1.x to accommodate this redirection : https://github.com/uclibs/scholar_uc/blob/master/app/jobs/import_url_job.rb

**Comment by mjgiarlo** [comment]
Thanks, @scherztc!

**Comment by mjgiarlo** [comment]
@jrgriffiniii I see this was added to the branch for @scherztc's PR. Do we still need to work on that PR, or should the work you did here have been applied to `master`?

**Comment by scherztc** [comment]
A reviewer can automatically rebase the driver/google branch with master in Github.  We can then remove the WIP and merge into master.  

https://github.com/samvera/browse-everything/pull/178

**Pull request merged**
