### PR TITLE
Fixes google drive empty web_content_link

### PR DESCRIPTION
**Pull request by scherztc**
Fixes: #177

The drive.get_file call needed a field parameter to get the web_content_link.

file = drive.get_file(id, fields: 'id, name, size, web_content_link')

### CODE REVIEW

**Comment by scherztc** [comment]
screen shot 2017-08-28 at 4 57 54 pm

Still getting a weird error message when downloading file and using web_content_link

**Comment by scherztc** [comment]
Might need to back port this 
https://github.com/samvera/hyrax/commit/f156ef24b11c9716165312531807cb8aeb57f2fe

**Comment by scherztc** [comment]
https://github.com/samvera/hyrax/blob/77140b38907158aaa4e30aae442ea5f04d0b1be2/app/jobs/import_url_job.rb#L53

I feel like URI isn't enough for Google Drive to work using the retriever.  I think we need more header information, particularly mime-type.  HTTPParty is returning the above error in my temp file.

**Comment by mjgiarlo** [comment]
@scherztc Why isn't this line automatically following the redirects?

https://github.com/samvera/browse-everything/blob/master/lib/browse_everything/retriever.rb#L75

In HTTParty, `follow_redirects` is set to `true` by default.

**Comment by mjgiarlo** [comment]
@scherztc @jrgriffiniii Rubocop now fails. Would someone mind tossing a commit at this branch to get the build green?

**Comment by scherztc** [comment]
@mjgiarlo I think BE is ignoring the follow_redirects because when Hyrax calls the retriever from the ImportUrlJob, it is only passing the uri and not including any header information.   Just my initial guess.

https://github.com/samvera/hyrax/blob/master/app/jobs/import_url_job.rb#L50-L58

**Comment by mjgiarlo** [comment]
@scherztc Looking through the BE and HTTParty internals, it's still not clear to me why they aren't dealing with this. I don't think they should need anything from Hyrax to do the right thing here.

**Comment by mjgiarlo** [comment]
But in any event, we'll need this branch fixed before we can move on to testing a new BE release in Hyrax.

**Pull request merged**
